name: Feature request
about: Suggest an idea or enhancement for H2Ready
labels: enhancement

body:
  - type: textarea
    attributes:
      label: Motivation
      description: Why is this change useful or necessary?
  - type: textarea
    attributes:
      label: Proposed Solution
